name=input("Enter your name:")
contact_no=input("Enter your contact number:")
email_id=input("Enter your Email id:")
birth_date=input("Enter you birth date:")
print("---Your Details---")
print("Name : ",name)
print("Contact Number:", contact_no)
print("Email id:",email_id)
print("Birthdate:",birth_date)